Modernize IT plugins to use annotations
apache/maven-integration-testing pull request #184
Opened 2022-07-07 08:18 UTC by gnodet

This is to be applied on top of #176.

2022-09-10 19:04 UTC, michael-o commented
@gnodet Kindly rebase.

2022-09-19 13:15 UTC, gnodet commented
> @gnodet Kindly rebase.

I plan to rebase on master once #176 is merged.

2022-10-06 20:20 UTC, slawekjaranowski commented on core-it-support/core-it-plugins/maven-it-plugin-fork/src/main/java/org/apache/maven/plugin/coreit/ForkGoalAggregatorMojo.java
> +            MavenProject executedProject = ( reactorProject ).getExecutionProject();
parentheses not needed

2022-10-06 20:20 UTC, slawekjaranowski commented on core-it-support/core-it-plugins/maven-it-plugin-no-default-comp/src/main/java/org/apache/maven/plugin/coreit/ItMojo.java
> +    @org.apache.maven.plugins.annotations.Component
import

2022-10-06 20:20 UTC, slawekjaranowski commented on core-it-support/core-it-plugins/maven-it-plugin-parameter-implementation/src/main/java/org/apache/maven/plugin/coreit/ParameterImplementationMojo.java
>   * @goal param-implementation
https://issues.apache.org/jira/browse/MPLUGIN-410

2022-10-06 20:43 UTC, gnodet commented on core-it-support/core-it-plugins/maven-it-plugin-active-collection/src/main/java/org/apache/maven/plugin/coreit/CheckMojo.java
> +    @org.apache.maven.plugins.annotations.Component
This is not doable.  The full declaration looks like:
```
    @org.apache.maven.plugins.annotations.Component
    private Map<String, Component> componentMap;
```
The `Component` interface is defined by at least 4 modules...

2022-10-07 06:32 UTC, slawekjaranowski commented on core-it-suite/pom.xml
> +            <version>3.3.0</version>
Is version needed here, in line 358 you remove version tag

2022-10-07 06:32 UTC, slawekjaranowski commented on core-it-suite/src/test/resources/mng-3652/test-plugin/pom.xml
> +<!--    </dependency>-->
please remove commented block

2022-10-10 17:49 UTC, gnodet commented
@slawekjaranowski would you mind having another look ?

2022-10-10 17:59 UTC, slawekjaranowski approved these changes

2022-10-10 20:16 UTC, michael-o commented
Looking through...

2022-10-10 20:44 UTC, michael-o requested changes
Massive!

2022-10-11 06:06 UTC, gnodet commented on core-it-support/core-it-plugins/maven-it-plugin-parameter-implementation/pom.xml
> +        <version>3.6.5-20221006.213415-47</version>
Ah, right.  Though we're never releasing this project, so not sure it's as much a problem...
I'll try to get a release of `maven-plugin-tools` out asap.  
@michael-o @slawekjaranowski any problem with a release ?

2022-10-11 06:45 UTC, slawekjaranowski commented on core-it-support/core-it-plugins/maven-it-plugin-parameter-implementation/pom.xml
> +        <version>3.6.5-20221006.213415-47</version>
@gnodet  - No problem with next releases, we have many resolved issues. 
Only open issues for next release should be reviewed.
Give me a day or two, I would like to look into it.

2022-10-24 15:33 UTC, gnodet commented on core-it-suite/src/test/resources/mng-3703/project/pom.xml
> +          <version>3.9.1</version>
Moved to latest.

2023-01-11 09:46 UTC, gnodet commented
Fwiw, this [commit](https://github.com/apache/maven-integration-testing/pull/184/commits/c4709de0e64a65a05c02db5c0ed2bb2ccf187a33) removes two ITs which [are not supported](https://issues.apache.org/jira/browse/MPLUGIN-435) by recent versions of the `maven-plugin-plugin`.

2023-01-11 10:52 UTC, cstamas approved these changes

2023-01-11 11:02 UTC, michael-o requested changes
Don't use `verifier.getSystemProperties().put(String, String)`, but `#AddCliArgument("-D....").

2023-01-11 11:33 UTC, gnodet commented
> verifier.getSystemProperties()



> Don't use `verifier.getSystemProperties().put(String, String)`, but `#AddCliArgument("-D....")`.

Please consider the fact that I haven't changed much code, and I certainly have not introduced such constructs.  These changes are unrelated to the current PR which is already quite big.  I'd rather not expand the focus of this PR too much.  It's already been sitting there for 6 months and the longer it waits the harder it will be to review / maintain.

2023-01-11 11:37 UTC, michael-o commented
> > verifier.getSystemProperties()
> 
> > Don't use `verifier.getSystemProperties().put(String, String)`, but `#AddCliArgument("-D....")`.
> 
> Please consider the fact that I haven't changed much code, and I certainly have not introduced such constructs. These changes are unrelated to the current PR which is already quite big. I'd rather not expand the focus of this PR too much. It's already been sitting there for 6 months and the longer it waits the harder it will be to review / maintain.

I agree, you are right. This is a separate topic.

2023-01-11 12:30 UTC, gnodet commented
> > > verifier.getSystemProperties()
> > 
> > 
> > > Don't use `verifier.getSystemProperties().put(String, String)`, but `#AddCliArgument("-D....")`.
> > 
> > 
> > Please consider the fact that I haven't changed much code, and I certainly have not introduced such constructs. These changes are unrelated to the current PR which is already quite big. I'd rather not expand the focus of this PR too much. It's already been sitting there for 6 months and the longer it waits the harder it will be to review / maintain.
> 
> I agree, you are right. This is a separate topic.

Also, `verifier.getProperties()` isn't deprecated, so it may be worth deprecating it...

2023-01-11 12:35 UTC, merged